#!/bin/bash
CONTAINER_NAME=plain_nginx
if [ `docker container ls  --format 'table {{.Names}}' |grep $CONTAINER_NAME` ]; then
  echo "Already running"
  exit
fi
if [ `docker container ls -a --format 'table {{.Names}}' | grep $CONTAINER_NAME` ]; then
	docker container restart $CONTAINER_NAME
	exit
fi

docker run --name $CONTAINER_NAME -v `pwd`/public:/usr/share/nginx/html:ro -d -p 80:80 nginx
